title: Warriors Back Page
author: Cody Box
email: coachcodybox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome place for fans, players and coaches to collobarate and find files.

# social links
twitter_username: @warriorsbb
github_username:  @baksterbox

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
